### PR TITLE
add japanese strings

### PR DESCRIPTION
**Pull request by aaharu**
Add strings for Japanese.

### CODE REVIEW

**Comment by aaharu** [comment]
Please check 🙏

**Comment by inverse** [comment]
Thanks for the work on this. It looks like some strings are still in English. Is this because they don't have a good translation or is there not enough context as to where they are used?

**Comment by HumbleBeeBumbleBee** [comment]
@aaharu I want to make the next release soon. Can you fix those missing translations?

**Comment by aaharu** [comment]
I fixed some translations.
Scrobble, Love, Now Playing, etc. are still English in Japanese Last.fm.

**Pull request merged**
