### PR TITLE
Update README.md and .travis.yml

### PR DESCRIPTION
**Pull request by a93-39a**
[Cannot Have Integration Until tgwizard Approves](https://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator)

### CODE REVIEW

**Comment by inverse** [comment]
If you're really passionate about this project I suggest we look to get it transformed from an owner to a team. A similar thing was done with the web-scrobbler project which I am part of. 

Will make things a lot easier: https://github.com/web-scrobbler/

**Comment by inverse** [comment]
Further more - with the new github actions that are coming that should make things fly a lot more.


See: https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

**Comment by a93-39a** [comment]
Sounds about right. I will ask tgwizard via email.
I don't know if he'll approve.
It would help several things like Travis Ci for example.

**Comment by a93-39a** [comment]
[New Github Team Prototype](https://github.com/simple-last-fm-scrobbler/simple-last-fm-scrobbler)
I am awaiting @tgwizard to ok the project change.

**Comment by inverse** [comment]
I think it works for projects like this :)

**Comment by a93h** [comment]
Super, thanks for the advice.

**Pull request merged**
