### PR TITLE
Added German translation…

### PR DESCRIPTION
**Pull request by herrherrmann**
… and set some strings to "untranslatable" (because they don't need to be translated).

### CODE REVIEW

**Comment by HumbleBeeBumbleBee** [comment]
Hi @herrherrmann Great!
Did you test it?
Any reason for putting it all in one file?

**Comment by herrherrmann** [comment]
Hey there. Yes, I tested it and it looked good on my HTC One S with Android 4.4.
And I worked with the [Translations Editor](https://developer.android.com/tools/studio/index.html#trans-editor) in Android Studio, therefore it outputs only one xml file. Do you want me to split it up? (Actually I'd rather suggest switching to the Translations Editor everywhere.)

Regarding the spacing: I'm not sure what you mean. Do I need to add artificial spacing? I didn't come across any problems on my device regarding those longer texts.

**Comment by HumbleBeeBumbleBee** [comment]
@herrherrmann I am OK with people adding different translation setups, I will change them if the app adds new screen with new strings.
When the time comes I might just have the main contributors decide which is me, @inverse and @metanota for now.
What do you think @inverse? All in single files or all separated?
Single Files:
PROs
Works with translations editor
One file
CONs
More work changing all previous files into single files.
Maybe harder to find strings and edit them

**Comment by bryansills** [comment]
I don't have a huge preference either way, but if we do decide to do the single file, we need to organize the strings in some kind of order. I think grouping them by Activity/Fragment/UI element makes sense, but if someone else has a better solution, I am all ears.

**Comment by inverse** [comment]
Personally I think having a single file containing all the translatable strings makes more sense. As for the ordering having them grouped logically is a win. Is the android translation editor able to generate new translation files with some ordering applied?

**Comment by herrherrmann** [comment]
Yep, that's the best practice, I guess (one `strings.xml` file).  
We could structure the sls strings by providing appropriate names for them! Example:  
```xml
<string
		name="common_ok">Ok</string>
	<string
		name="common_close">Close</string>
	<string
		name="common_remove">Remove</string>
<!-- ... -->
<!-- Now the strings from strings_about.xml: -->
<string
        name="about_app_name" translatable="false">Simple Last.fm Scrobbler</string>
    <string
        name="about_by">by</string>
    <string
        name="about_email_addr" translatable="false">simple.lfm.scrobbler@gmail.com</string>
<!-- ... and so forth. -->
```

**Comment by HumbleBeeBumbleBee** [comment]
I will put all the strings in single files seperated by
* strings.xml                                                               
* strings_about.xml                                                         
* strings_cache.xml                                                         
* strings_creds.xml                                                         
* strings_mapis.xml                                                         
* strings_options.xml                                                       
* strings_status.xml

**Pull request merged**
