### PR TITLE
Database Failure On Install

### PR DESCRIPTION
**Pull request by a93-39a**
Patch

### CODE REVIEW

**Comment by inverse** [comment]
Why are binaries being added? Shouldn't we have some CI setup to build from master/branches?

**Comment by a93-39a** [comment]
Do you recommend Travis Cli or something else?

**Comment by inverse** [comment]
Binaries should be included as part of the tagging/release cycle.

No experience with travis for android but looks possible.

https://docs.travis-ci.com/user/languages/android/

We already have some script in this repo, not sure how up to date it works.

**Comment by a93-39a** [comment]
[Cannot Have Integration Until tgwizard Approves](https://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator)

**Pull request merged**
