### PR TITLE
Enable submitting MusicBrainz Recording ID

### PR DESCRIPTION
**Pull request by Freso**
I have not tested this at all, but discussion in https://github.com/tgwizard/sls/issues/421 has not provided a reason why the code wouldn't work. Submitting as a PR in the hope that this can get the code tested and move this issue along to hopefully get it fixed.

Fixes https://github.com/tgwizard/sls/issues/421

### CODE REVIEW

**Comment by dotWee** [comment]
I'll try to validate it's functionality later this day. Any other reason why this isn't merged yet?

**Comment by Freso** [comment]
Well, I don't know why this was commented out to begin with. :) Literally all I'm doing is un-commenting out some code from https://github.com/tgwizard/sls/commit/d7ab95f7bbaa6f654ab5c7147c3198e13feaed8f by @HumbleBeeBumbleBee, but it doesn't have any commentary or notes that I could find for why it was commented out to begin with.

**Comment by Freso** [comment]
@tgwizard @dotWee has confirmed that the Recording MBID submission works fine. Anything else needed to get this PR merged?

**Comment by Freso** [comment]
Would be nice to test if it actually submits the Recording MBIDs, which I don't think Spotify will/would do?

**Comment by inhji** [comment]
It doesn’t work for me, I’m on Android 9 and using Phonograph as my music player. I compiled your version of sls and tried submitting a few tracks to Listenbrainz. In my case, the MBID does not get submitted (I checked with [picard](https://picard.musicbrainz.org/) to see if it actually exists in the metadata of my mp3s).

Logcat output from sls:


    05-15 09:47:17.004 D/ScrobblingService(17740): State: RESUME
    05-15 09:47:17.007 D/ScrobblingService(17740): Will try to queue track, played: 256845 vs 125440
    05-15 09:47:17.009 D/ScrobblingService(17740): queued track after playtime: 256845
    05-15 09:47:17.010 D/ScrobblingService(17740): Track [mTrack=Progress, mArtist=Disasterpeace, mAlbum=FEZ, mDuration=256, mMbId=, mMusicAPI=MusicAPI [clashWithScrobbleDroid=1, enabled=1, id=1, msg=null, name=Phonograph, pkg=com.kabouzeid.gramophone], mQueued=true, mRating=, mRowId=-1, mSource=P, mTimePlayed=256845, mTracknr=4, mUnknownDuration=false, mWhen=1557906180, mWhenToCountTimeFrom=410865526]
    05-15 09:47:17.010 D/ScrobblingService(17740): inserting scrobble: ListenBrainz

API Repsponse of the same song:


             {
                "listened_at":1557906180,
                "recording_msid":"fa9ae023-cdef-44bb-bc95-d95e983ff415",
                "track_metadata":{
                   "additional_info":{
                      "artist_mbids":[

                      ],
                      "artist_msid":"9063f2de-8e91-41aa-9e9f-31ef05130882",
                      "isrc":null,
                      "recording_mbid":null,
                      "recording_msid":"fa9ae023-cdef-44bb-bc95-d95e983ff415",
                      "release_group_mbid":null,
                      "release_mbid":null,
                      "release_msid":"1bb4dfb7-23e8-41f6-bf29-a1b6324f3ece",
                      "spotify_id":null,
                      "tags":[

                      ],
                      "track_mbid":null,
                      "tracknumber":null,
                      "work_mbids":[

                      ]
                   },
                   "artist_name":"Disasterpeace",
                   "release_name":"FEZ",
                   "track_name":"Progress"
                },
                "user_name":"inhji"
             }

(Originally published at: https://inhji.de/posts/it-doesn-t-work-L-J0M)

**Comment by Freso** [comment]
@inhji Can you confirm that Phonograph actually makes the MBIDs available? (Simple Last.FM Scrobbler doesn’t read the tags from the files directly, but gets the information from what is being made available by the player. If the player doesn’t provide the MBIDs, SLS can’t get them and thus can’t submit them either…)

**Comment by inhji** [comment]
@Fresco After some digging I’m pretty sure that it does not. I did test some other players and none of them send the mbid.. (what I did was checking the keys in the bundle that gets sent with the intent that sls receives)

Do you know of any app that is known for sending the mbid?

(Originally published at: https://inhji.de/posts/atfresco-after-so-3UwYA)

**Comment by a93-39a** [comment]
Hello everyone,
I just noticed this.
I am adding it, however I noticed most apps do not use mbid.
What's the world coming to? I know..
Either way, I made this change manually for the next build.

**Comment by a93-39a** [comment]
Closing pull request.

**Pull request closed without merging**
