### PR TITLE
Scrobblers correctly handles track switching.

### LINKED ISSUE #44: SLS can't scrobble the same track played consecutively in the default player
This is due to the fact that the default player only sends one* kind of event: "Something has changed". It is therefore impossible to determine if the track has been paused, resumed, started, stopped, started again, etc. Also, the intent doesn't contain the track duration, so the play state info cannot be deduced from that.

*there is another kind of intent sent when an entire playlist finishes. So, a playlist with only one track set on repeat works fine.

### LINKED ISSUE #129: Ignores some songs
When playing music some songs will be sent to the scrobble cache/scrobbled, other songs won't. It's not always the same songs that get ignored, it appears to be random. It makes it kind of useless. Worked just right until a few weeks ago. Tried updating and reinstalling. I'm using the default android music player on an android 2.3.7 device.

### PR DESCRIPTION
**Pull request by metanota**
Hi.
This is the humble reincarnation of pull request #100. It fixed #44 and #99 for the most of the players.
Also I couldn't reproduce an issue with Google Play Music that @bmos have mentioned, so either developers have fixed it or I just forgot the correct scenario for it.
This fix doesn't resolve problems for all of the players which seem to be impossible, but I hope it helps in most of the cases.
I've checked it in PowerAmp, Google Play Music and Player Pro on SGS III. It'll be very helpful If some of you could also try this fix on your devices/players.

Also it may fixes #129. I've mentioned similar problem on vanilla sls and it never happened again since I'm using my fix to scrobble the music. It's definitely worth to double-check this.

### CODE REVIEW

**Comment by HumbleBeeBumbleBee** [comment]
@metanota I have had the same problem. It occurs in most Receivers. I am currently working on a Spotify Receiver and it doesn't scrobble when the same song is played on repeat (offline or online) for Premium Users.
Maybe you could take a look. I am not sure how to fix it...

**Comment by JohnMaguire** [comment]
:+1:

**Comment by HumbleBeeBumbleBee** [comment]
I think there's one probably with this merger with SamsungMusicReceiver.java that I modified recently.
I will quickly test and merge this.

**Comment by HumbleBeeBumbleBee** [comment]
OK the latest version of SLS with #149 https://github.com/tgwizard/sls/tree/testing-149 please test it!
I'll try testing as many application as I can.
It'd be great if people could list application tested and verified as working.

I couldn't find Winamp player though...

Also @metanota when everything I working and people report it working I was hoping you could fork `testing-149` and make a pull request so I can give you credit. My git skills are limited sorry. Then I'll delete testing-149.

**Comment by HumbleBeeBumbleBee** [comment]
Hey @metanota could you fork https://github.com/tgwizard/sls/tree/testing-149 to your own repository so you can make a pull request and take credit?

**Comment by HumbleBeeBumbleBee** [comment]
Just merged it...

**Comment by HumbleBeeBumbleBee** [comment]
Looks like launching VLC or Spotify causes SLS to crash for versions after #149.
Can anybody else confirm this?
I am going to add the code for Spotify and SoundCloud to make sure it's just #149 
Also, I was having a lot of scrobbling issues before #149 or #191

**Comment by HumbleBeeBumbleBee** [comment]
Looks Spotify and SoundCloud don't really work without patch #149 anyways.

**Comment by HumbleBeeBumbleBee** [comment]
Turns out I am still having scrobbling issues, but libre.fm is scrobbling just whereas last.fm is not.

**Comment by metanota** [comment]
@HumbleBeeBumbleBee I'll look into VLC issue. Have you any exception logs about it?
> All my scrobbling went back to normal after switching back to before #149 or #191 

What other problems did you have with these changes?

**Comment by HumbleBeeBumbleBee** [comment]
Sorry, it seems like it's a new problem with SLS and 8tracks.
I am going to implement #149 on the next release.

**Comment by metanota** [comment]
I should definitely try 8tracks then :)

**Comment by HumbleBeeBumbleBee** [comment]
I found the problem @metanota 
Bad news: I have wasted your time.
Good news: I think we can apply your patches.
https://github.com/tgwizard/sls/issues/144/#issuecomment-101445225

**Comment by HumbleBeeBumbleBee** [comment]
@metanota is there any reason you didn't change SamsungMusicReceiver.java ?

**Pull request closed without merging**
