### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by bryansills**
Updated icon that I made, inspired by Material Design. I originally wanted to just clean up the icon files, but I realized that they were in a bad state and the accompanying art was out of date as well. So I remade the icon in Illustrator, using Last.fm's design resources. I changed up the colors so that one matches the color defined by Last.fm (#d51007) and one that is more Material-y (#ef5350). Finally, I used [Android Asset Studio](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html) to give it a nice background and fancy shadows.

I'm open to suggestions on the icon. If you don't like the colors, or want something different, you won't hurt my feelings.

### CODE REVIEW

**Comment by luisbandalap** [comment]
looks nice, it suits material desing, but now we need material design in the interface :smiley:

**Comment by bryansills** [comment]
Yeah... I was gonna make another pull request in the next week or so using the AppCompat library to bring Material-y goodness to all devices.

**Comment by HumbleBeeBumbleBee** [comment]
@inverse @metanota what do you guys think about the new icon
I like it. I will kind of miss the transparent background but I like the new round-edge squared background just as well.
@bryansills I am interested in making this pull request, and your [AppCompat](https://github.com/bryansills/sls/tree/appcompat), whenever you're ready. I will merge your pull requests before I make the changes I want to make in:
* IssueSummary.md , changelog.txt, SoundCloudReceiver.java, AndroidManifest.xml, #149 and #110

**Comment by inverse** [comment]
I think it's nice :+1: 

 I really need to invest in a new phone so I can help out with the project more. Was hoping for a date on the nexus 5 2015 edition but I'm guessing it's still a while off :/

**Comment by HumbleBeeBumbleBee** [comment]
@bryansills If you want I can modify them after, but the following will be changed by you or I after I merge this pull request.
https://github.com/tgwizard/sls/search?utf8=%E2%9C%93&q=Tha+PHLASH+about.xml&type=Code

**Comment by bryansills** [comment]
Whoops. Knew I forgot something. I'll take those out in the morning.

**Comment by HumbleBeeBumbleBee** [comment]
It's ok, I must modify them anyways, updated license. #49

**Comment by HumbleBeeBumbleBee** [comment]
Also did you want to put your icon in the top directory or leave [this one](https://github.com/tgwizard/sls/blob/master/icon_512.png) or have both?

**Comment by bryansills** [comment]
I made all the changes. It is ready to be pulled in.

My AppCompat branch needs some more work. I'll made a few pull requests when that work is ready.

**Comment by HumbleBeeBumbleBee** [comment]
Pull looks good. Thanks.

**Pull request merged**
